insert into EXECUTOR (NAME) values ('Modern Talking');
insert into EXECUTOR (NAME) values ('Blue System');
insert into EXECUTOR (NAME) values ('The Rolling Stones');
insert into EXECUTOR (NAME) values ('The Beatles');
insert into EXECUTOR (NAME) values ('Баста');
insert into EXECUTOR (NAME) values ('Pharaoh');
insert into EXECUTOR (NAME) values ('Бетховен');
insert into EXECUTOR (NAME) values ('Моцарт');
insert into EXECUTOR (NAME) values ('Би Би Кинг');
insert into EXECUTOR (NAME) values ('Эрик Клэптон');

insert into GENRE (TITLE) values ('POP');
insert into GENRE (TITLE) values ('ROCK');
insert into GENRE (TITLE) values ('RAP');
insert into GENRE (TITLE) values ('CLASSIC');
insert into GENRE (TITLE) values ('BLUES');

insert into ALBUM (TITLE, year_of_issue) values ('Lets talk about love', 1985);
insert into ALBUM (TITLE, year_of_issue) values ('The First Album', 1985);
insert into ALBUM (TITLE, year_of_issue) values ('Alone', 1999);
insert into ALBUM (TITLE, year_of_issue) values ('Ready For Romance', 1986);
insert into ALBUM (TITLE, year_of_issue) values ('In The Middle Of Nowhere', 1986);
insert into ALBUM (TITLE, year_of_issue) values ('Back for Good', 1998);
insert into ALBUM (TITLE, year_of_issue) values ('Romantic Warrios', 1987);
insert into ALBUM (TITLE, year_of_issue) values ('Victory', 2002);
insert into ALBUM (TITLE, year_of_issue) values ('Walking on a Rainbow', 1987);
insert into ALBUM (TITLE, year_of_issue) values ('Body Heat', 1988);
insert into ALBUM (TITLE, year_of_issue) values ('Twilight', 1989);
insert into ALBUM (TITLE, year_of_issue) values ('Obsession', 1990);
insert into ALBUM (TITLE, year_of_issue) values ('Seeds of Heaven', 1991);
insert into ALBUM (TITLE, year_of_issue) values ('Hello America', 1992);
insert into ALBUM (TITLE, year_of_issue) values ('Backstreet Dreams', 1993);
insert into ALBUM (TITLE, year_of_issue) values ('X-Ten', 1994);
insert into ALBUM (TITLE, year_of_issue) values ('Sticky Fingers', 1971);
insert into ALBUM (TITLE, year_of_issue) values ('Exile on Main St', 1972);
insert into ALBUM (TITLE, year_of_issue) values ('Tattoo You', 1981);
insert into ALBUM (TITLE, year_of_issue) values ('Aftermath', 1966);
insert into ALBUM (TITLE, year_of_issue) values ('Beggars Banquet', 1968);
insert into ALBUM (TITLE, year_of_issue) values ('Black and Blue', 1976);
insert into ALBUM (TITLE, year_of_issue) values ('Goats Head Soup', 1973);
insert into ALBUM (TITLE, year_of_issue) values ('Let it Bleed', 1969);
insert into ALBUM (TITLE, year_of_issue) values ('Abbey Road', 1969);
insert into ALBUM (TITLE, year_of_issue) values ('Revolver', 1966);
insert into ALBUM (TITLE, year_of_issue) values ('Help!', 1965);
insert into ALBUM (TITLE, year_of_issue) values ('A Hard Days Night', 1964);
insert into ALBUM (TITLE, year_of_issue) values ('Please Please Me', 1963);
insert into ALBUM (TITLE, year_of_issue) values ('Rubber Soul', 1965);
insert into ALBUM (TITLE, year_of_issue) values ('Let it Be', 1970);
insert into ALBUM (TITLE, year_of_issue) values ('Meet the Beatles!', 1964);
insert into ALBUM (TITLE, year_of_issue) values ('40', 2020);
insert into ALBUM (TITLE, year_of_issue) values ('Баста 5, часть 1', 2016);
insert into ALBUM (TITLE, year_of_issue) values ('Баста 5, часть 2', 2016);
insert into ALBUM (TITLE, year_of_issue) values ('Баста/Смоки мо', 2015);
insert into ALBUM (TITLE, year_of_issue) values ('Баста 4', 2013);
insert into ALBUM (TITLE, year_of_issue) values ('Баста/Гуф', 2010);
insert into ALBUM (TITLE, year_of_issue) values ('Баста 3', 2010);
insert into ALBUM (TITLE, year_of_issue) values ('Баста 2', 2007);
insert into ALBUM (TITLE, year_of_issue) values ('Million Dollar Depression', 2021);
insert into ALBUM (TITLE, year_of_issue) values ('Правило', 2020);
insert into ALBUM (TITLE, year_of_issue) values ('Phuneral', 2018);
insert into ALBUM (TITLE, year_of_issue) values ('REDЯUM', 2018);
insert into ALBUM (TITLE, year_of_issue) values ('Pink Phloyd', 2017);
insert into ALBUM (TITLE, year_of_issue) values ('Phosphor', 2016);
insert into ALBUM (TITLE, year_of_issue) values ('Плакшери', 2016);
insert into ALBUM (TITLE, year_of_issue) values ('Dolor', 2015);
insert into ALBUM (TITLE, year_of_issue) values ('Sonatas', 1821);
insert into ALBUM (TITLE, year_of_issue) values ('Septet For Strings And Winds In E Flat', 1820);
insert into ALBUM (TITLE, year_of_issue) values ('Sonata in D Major', 1830);
insert into ALBUM (TITLE, year_of_issue) values ('Les sonates de Beethoven par Yves Nat', 1832);
insert into ALBUM (TITLE, year_of_issue) values ('The Piano Concertos in under 10', 1820);
insert into ALBUM (TITLE, year_of_issue) values ('Sonata in C Sharp Minor Op. 27', 1830);
insert into ALBUM (TITLE, year_of_issue) values ('Trio for 2 Oboes and English Horn in C major', 1835);
insert into ALBUM (TITLE, year_of_issue) values ('Sonate Les Adieux', 1825);
insert into ALBUM (TITLE, year_of_issue) values ('Mica Serenadă', 1787);
insert into ALBUM (TITLE, year_of_issue) values ('Sonata in A Major, K. 331', 1788);
insert into ALBUM (TITLE, year_of_issue) values ('Quatre Trios Vocaux', 1786);
insert into ALBUM (TITLE, year_of_issue) values ('Symphony No.39 in E-flat major, K.543', 1790);
insert into ALBUM (TITLE, year_of_issue) values ('Ave, verum corpus / Wiegenlied', 1789);
insert into ALBUM (TITLE, year_of_issue) values ('Ránki: Pomádé király új ruhája - Szenkár', 1791);
insert into ALBUM (TITLE, year_of_issue) values ('Dupont Variationen KV 573', 1800);
insert into ALBUM (TITLE, year_of_issue) values ('Verdi: Don Carlos, Trubadúr - Liszt', 1789);
insert into ALBUM (TITLE, year_of_issue) values ('Lucille', 1986);
insert into ALBUM (TITLE, year_of_issue) values ('Live at the Regal', 1965);
insert into ALBUM (TITLE, year_of_issue) values ('Live in Cook Country Jail', 1971);
insert into ALBUM (TITLE, year_of_issue) values ('Completely Well', 1969);
insert into ALBUM (TITLE, year_of_issue) values ('Deuces Wild', 1997);
insert into ALBUM (TITLE, year_of_issue) values ('Live&Well', 1969);
insert into ALBUM (TITLE, year_of_issue) values ('Blues Summit', 1993);
insert into ALBUM (TITLE, year_of_issue) values ('Midnigth Believer', 1978);
insert into ALBUM (TITLE, year_of_issue) values ('Unplugged', 1992);
insert into ALBUM (TITLE, year_of_issue) values ('461 Ocean Boulevard', 1974);
insert into ALBUM (TITLE, year_of_issue) values ('Slowhand', 1977);
insert into ALBUM (TITLE, year_of_issue) values ('Journeyman', 1989);
insert into ALBUM (TITLE, year_of_issue) values ('Pilgrim', 1998);
insert into ALBUM (TITLE, year_of_issue) values ('August', 1986);
insert into ALBUM (TITLE, year_of_issue) values ('Backless', 1978);
insert into ALBUM (TITLE, year_of_issue) values ('Rush', 1992);
insert into ALBUM (TITLE, year_of_issue) values ('Body to Body', 1996);

insert into COMPILATION (TITLE, year_of_issue) values ('The Best of Modern Talking', 2020);
insert into COMPILATION (TITLE, year_of_issue) values ('Top Hits', 2015);
insert into COMPILATION (TITLE, year_of_issue) values ('Greatest Hits', 1964);
insert into COMPILATION (TITLE, year_of_issue) values ('The Beatles Box', 1980);
insert into COMPILATION (TITLE, year_of_issue) values ('Лучшие Треки', 2019);
insert into COMPILATION (TITLE, year_of_issue) values ('Все Лучшие Треки', 2021);
insert into COMPILATION (TITLE, year_of_issue) values ('Лучшее из Бетховена', 2017);
insert into COMPILATION (TITLE, year_of_issue) values ('The Best', 2013);
insert into COMPILATION (TITLE, year_of_issue) values ('B.B.King&Blues Brothers', 1997);
insert into COMPILATION (TITLE, year_of_issue) values ('Eric Clapton’s Rainbow Concert', 1973);

insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('You are my heart, you are my soul', 91, 2);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Gerominos Cadillac', 256, 5);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Magic Symphony', 299, 10);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Love Suit', 100, 12);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Gimme Shelter', 245, 20);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Angie', 95, 22);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Let it Be', 289, 30);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Hey Jude', 95, 28);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Сансара', 93, 35);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Неболей', 299, 37);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Дико, например', 276, 41);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Blood Oceans', 276, 47);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Лунная Соната', 175, 50);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Egmont, Op.84', 186, 55);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Симфония №40', 95, 60);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Турецкий марш', 187, 63);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('The Thrill is Gone', 128, 67);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('When Love Comes to Town', 194, 70);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Wonderful Tonight', 299, 74);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Layla', 98, 79);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('My bed is too big', 250, 10);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Atlantis is calling', 187, 5);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('48 Hours', 150, 12);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Love me on the Rocks', 95, 12);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Моя игра', 93, 33);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Моя ЖИЗНЬ', 95, 33);
insert into TRACK (TITLE, DURATION, ALBUM_ID) values ('Cheri Cheri Lady', 250, 5);

insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (1, 1);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (1, 2);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (2, 3);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (2, 4);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (3, 5);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (3, 6);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (4, 7);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (4, 8);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (5, 9);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (5, 10);
insert into GENREEXECUTOR (GENRE_ID, EXECUTOR_ID) values (2, 1);

insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (1, 1);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (2, 1);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (3, 1);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (4, 1);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (5, 1);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (6, 1);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (7, 1);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (8, 1);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (9, 2);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (10, 2);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (11, 2);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (12, 2);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (13, 2);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (14, 2);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (15, 2);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (16, 2);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (17, 3);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (18, 3);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (19, 3);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (20, 3);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (21, 3);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (22, 3);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (23, 3);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (24, 3);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (25, 4);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (26, 4);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (27, 4);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (28, 4);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (29, 4);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (30, 4);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (31, 4);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (32, 4);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (33, 5);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (34, 5);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (35, 5);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (36, 5);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (37, 5);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (38, 5);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (39, 5);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (40, 5);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (41, 6);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (42, 6);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (43, 6);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (44, 6);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (45, 6);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (46, 6);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (47, 6);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (48, 6);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (49, 7);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (50, 7);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (51, 7);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (52, 7);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (53, 7);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (54, 7);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (55, 7);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (56, 7);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (57, 8);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (58, 8);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (59, 8);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (60, 8);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (61, 8);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (62, 8);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (63, 8);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (64, 8);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (65, 9);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (66, 9);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (67, 9);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (68, 9);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (69, 9);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (70, 9);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (71, 9);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (72, 9);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (73, 10);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (74, 10);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (75, 10);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (76, 10);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (77, 10);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (78, 10);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (79, 10);
insert into ALBUMEXECUTOR (ALBUM_ID, EXECUTOR_ID) values (80, 10);

insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (1, 1);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (2, 1);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (3, 2);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (4, 2);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (5, 3);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (6, 3);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (7, 4);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (8, 4);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (9, 5);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (10, 5);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (11, 6);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (12, 6);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (13, 7);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (14, 7);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (15, 8);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (16, 8);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (17, 9);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (18, 9);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (19, 10);
insert into TRACKCOMPILATION (TRACK_ID, COMPILATION_ID) values (20, 10);